### ISSUE TITLE
userStakedBalanceOfAt set in place of totalStakedBalanceOfAt

### ISSUE THREAD

**Issue by izyak** [openmoneymarket/openmoneymarket-mono#288]
Snapshot for total staked balance is being set to snapshot balance of user in OMM Token snapshot.

**Comment by redlarva** [comment]
Contract updated  and the total of staked OMM set to `24404682485167754779968750`  for the timestamp of `1644899882101000` 
(snapshot timestamp for OIP - 8 OMM Monks DAO Fund)

[transaction](https://tracker.icon.foundation/transaction/0x92a3afa13192f294f8a690fe8fb6bb9b06c991d1d457250affc9fb973789b22a)
